server:
  # tomcat配置
  tomcat:
    uri-encoding: UTF-8
    threads:
      max: 200
      min-spare: 30
    connection-timeout: 5000ms
  # 服务端口号
  port: 9000
  # url前缀
  servlet:
    context-path: /haw-api
spring:
  application:
    name: haw-server
  # MySQL Druid数据源配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/haw?useUnicode=true&charcterEncoding=utf8mb4&serverTimezone=Asia/Shanghai
      username: root
      password: 1015
      initial-size: 8
      max-active: 16
      min-idle: 8
      max-wait: 60000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
  # redis数据源配置
  redis:
    database: 0
    host: localhost
    port: 6379
    password: xiguapi777
    jedis:
      pool:
        max-active: 1000
        max-wait: -1ms
        max-idle: 16
        min-idle: 8
  data:
    # MongoDB数据源配置
    mongodb:
      host: localhost
      port: 27017
      database: haw
      authentication-database: admin
      username: xiguapi
      password: xiguapi777
# MyBatis配置
mybatis:
  mapper-locations:
    - classpath*:mapper/*.xml
  type-aliases-package: cloud.xiguapi.haw.db.model
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
# 配置日志输出
logging:
  level:
    root: info
    cloud.xiguapi.haw.db.mapper: warn
  pattern:
    console: "%d{HH:mm:ss} %-5level %msg%n"